// @generated by scripts/build-edge-engine.mjs from src/engine-entry.ts — do not edit by hand.


// src/constants.ts
var MAX_MAP_WIDTH = 1e3;
var MAX_MAP_HEIGHT = 1e3;
var MAP_WIDTH = MAX_MAP_WIDTH;
var MAP_HEIGHT = MAX_MAP_HEIGHT;
var UNIT_STATS = {
  soldier: { hp: 60, speed: 100, damage: 10, range: 120, radius: 10, fireCooldown: 1, projectileSpeed: 300, projectileRadius: 5, turnSpeed: 2.5 },
  blade: { hp: 80, speed: 120, damage: 12, range: 25, radius: 12, fireCooldown: 0.5, projectileSpeed: 600, projectileRadius: 3, turnSpeed: 3 },
  sniper: { hp: 15, speed: 70, damage: 30, range: 300, radius: 7, fireCooldown: 2.5, projectileSpeed: 1200, projectileRadius: 5, turnSpeed: 1.2 },
  zombie: { hp: 20, speed: 55, damage: 14, range: 20, radius: 8, fireCooldown: 0.8, projectileSpeed: 300, projectileRadius: 4, turnSpeed: 3 },
  shielder: { hp: 40, speed: 45, damage: 10, range: 20, radius: 11, fireCooldown: 1, projectileSpeed: 300, projectileRadius: 4, turnSpeed: 2 },
  bomber: { hp: 25, speed: 50, damage: 0, range: 0, radius: 9, fireCooldown: 99, projectileSpeed: 0, projectileRadius: 0, turnSpeed: 3 }
};
var ARMY_COMPOSITION = [
  { type: "soldier", count: 3 },
  { type: "sniper", count: 1 }
];
var ROUND_DURATION_S = 6;
var COVER_SCREEN_DURATION_MS = 1500;
var ELEVATION_RANGE_BONUS = 0.2;
var FLANK_ANGLE_THRESHOLD = Math.PI / 3;
var FLANK_DAMAGE_MULTIPLIER = 1.5;
var SHIELD_MAX_HITS = 7;
var COLLISION_HITBOX_SCALE = 0.8;
var CTF_FLAG_PICKUP_RADIUS = 25;
var CTF_BASE_ZONE_WIDTH = 100;
var CTF_ARMY_COMPOSITION = [
  { type: "soldier", count: 3 }
];

// src/online-types.ts
var MAX_ONLINE_UNITS = 100;
var MAX_ONLINE_OBSTACLES = 300;
var MAX_ONLINE_ELEVATION_ZONES = 300;

// src/units.ts
function segmentHitsRect(a, b, rect, padding) {
  const left = rect.x - padding;
  const right = rect.x + rect.w + padding;
  const top = rect.y - padding;
  const bottom = rect.y + rect.h + padding;
  const dx = b.x - a.x;
  const dy = b.y - a.y;
  let tMin = 0;
  let tMax = 1;
  if (Math.abs(dx) < 1e-8) {
    if (a.x < left || a.x > right) return false;
  } else {
    let t1 = (left - a.x) / dx;
    let t2 = (right - a.x) / dx;
    if (t1 > t2) {
      const tmp = t1;
      t1 = t2;
      t2 = tmp;
    }
    tMin = Math.max(tMin, t1);
    tMax = Math.min(tMax, t2);
    if (tMin > tMax) return false;
  }
  if (Math.abs(dy) < 1e-8) {
    if (a.y < top || a.y > bottom) return false;
  } else {
    let t1 = (top - a.y) / dy;
    let t2 = (bottom - a.y) / dy;
    if (t1 > t2) {
      const tmp = t1;
      t1 = t2;
      t2 = tmp;
    }
    tMin = Math.max(tMin, t1);
    tMax = Math.min(tMax, t2);
    if (tMin > tMax) return false;
  }
  return true;
}
function pointHitsObstacle(p, obstacles, padding) {
  return obstacles.some((obs) => {
    const cx = Math.max(obs.x, Math.min(obs.x + obs.w, p.x));
    const cy = Math.max(obs.y, Math.min(obs.y + obs.h, p.y));
    const dx = p.x - cx;
    const dy = p.y - cy;
    return dx * dx + dy * dy < padding * padding;
  });
}
function detourWaypoints(a, b, obstacles, padding, depth = 0) {
  const MAX_DEPTH = 10;
  if (depth >= MAX_DEPTH) return [];
  let firstObs = null;
  let firstT = Infinity;
  for (const obs2 of obstacles) {
    if (!segmentHitsRect(a, b, obs2, padding)) continue;
    const cx = obs2.x + obs2.w / 2;
    const cy = obs2.y + obs2.h / 2;
    const sx = b.x - a.x;
    const sy = b.y - a.y;
    const len2 = sx * sx + sy * sy;
    const t = len2 > 0 ? ((cx - a.x) * sx + (cy - a.y) * sy) / len2 : 0;
    if (t < firstT) {
      firstT = t;
      firstObs = obs2;
    }
  }
  if (!firstObs) return [];
  const obs = firstObs;
  const cp = padding + 3;
  const corners = [
    { x: obs.x - cp, y: obs.y - cp },
    { x: obs.x + obs.w + cp, y: obs.y - cp },
    { x: obs.x - cp, y: obs.y + obs.h + cp },
    { x: obs.x + obs.w + cp, y: obs.y + obs.h + cp }
  ];
  const validCorners = corners.map((c) => ({
    x: Math.max(padding, Math.min(MAP_WIDTH - padding, c.x)),
    y: Math.max(padding, Math.min(MAP_HEIGHT - padding, c.y))
  })).filter((c) => !pointHitsObstacle(c, obstacles, padding));
  if (validCorners.length === 0) {
    const edgeMids = [
      { x: obs.x + obs.w / 2, y: obs.y - cp },
      { x: obs.x + obs.w / 2, y: obs.y + obs.h + cp },
      { x: obs.x - cp, y: obs.y + obs.h / 2 },
      { x: obs.x + obs.w + cp, y: obs.y + obs.h / 2 }
    ];
    const fallback = edgeMids.map((c) => ({
      x: Math.max(padding, Math.min(MAP_WIDTH - padding, c.x)),
      y: Math.max(padding, Math.min(MAP_HEIGHT - padding, c.y))
    })).filter((c) => !pointHitsObstacle(c, obstacles, padding));
    if (fallback.length === 0) return [];
    validCorners.push(...fallback);
  }
  let bestCorner = validCorners[0];
  let bestDist = Infinity;
  for (const c of validCorners) {
    const dist2 = Math.hypot(c.x - a.x, c.y - a.y) + Math.hypot(b.x - c.x, b.y - c.y);
    if (dist2 < bestDist) {
      bestDist = dist2;
      bestCorner = c;
    }
  }
  if (Math.hypot(bestCorner.x - a.x, bestCorner.y - a.y) < 2) return [];
  const before = detourWaypoints(a, bestCorner, obstacles, padding, depth + 1);
  const after = detourWaypoints(bestCorner, b, obstacles, padding, depth + 1);
  return [...before, bestCorner, ...after];
}
function createUnit(id, type, team, pos) {
  const stats = UNIT_STATS[type];
  return {
    id,
    type,
    team,
    pos: { ...pos },
    hp: stats.hp,
    maxHp: stats.hp,
    speed: stats.speed,
    damage: stats.damage,
    range: stats.range,
    radius: stats.radius,
    moveTarget: null,
    waypoints: [],
    attackTargetId: null,
    alive: true,
    fireCooldown: stats.fireCooldown,
    fireTimer: 0,
    projectileSpeed: stats.projectileSpeed,
    projectileRadius: stats.projectileRadius,
    vel: { x: 0, y: 0 },
    gunAngle: team === "blue" ? -Math.PI / 2 : Math.PI / 2,
    turnSpeed: stats.turnSpeed,
    damageReduction: type === "blade" ? 0.3 : void 0
  };
}
function createUnitFromState(s) {
  const unit = createUnit(s.id, s.type, s.team, { x: s.x, y: s.y });
  unit.hp = s.hp;
  unit.maxHp = s.maxHp;
  unit.gunAngle = s.gunAngle;
  unit.alive = s.hp > 0;
  unit.speed = s.speed;
  unit.range = s.range;
  return unit;
}
function nudgeOutOfBlocks(pos, blocks, padding = 4) {
  for (const b of blocks) {
    const left = b.x - padding;
    const right = b.x + b.w + padding;
    const top = b.y - padding;
    const bottom = b.y + b.h + padding;
    if (pos.x > left && pos.x < right && pos.y > top && pos.y < bottom) {
      const dLeft = pos.x - left;
      const dRight = right - pos.x;
      const dTop = pos.y - top;
      const dBottom = bottom - pos.y;
      const min = Math.min(dLeft, dRight, dTop, dBottom);
      if (min === dLeft) return { x: left, y: pos.y };
      if (min === dRight) return { x: right, y: pos.y };
      if (min === dTop) return { x: pos.x, y: top };
      return { x: pos.x, y: bottom };
    }
  }
  return pos;
}
function flankScore(attackerPos, targetPos, targetGunAngle) {
  const approachAngle = Math.atan2(attackerPos.y - targetPos.y, attackerPos.x - targetPos.x);
  let diff = approachAngle - targetGunAngle;
  diff = (diff + Math.PI) % (2 * Math.PI) - Math.PI;
  if (diff < -Math.PI) diff += 2 * Math.PI;
  return Math.abs(diff) / Math.PI;
}
function generateRandomComposition() {
  const pool = [
    { type: "soldier", weight: 2.5 },
    { type: "sniper", weight: 1 },
    { type: "shielder", weight: 0.5 }
  ];
  const totalWeight = pool.reduce((sum, p) => sum + p.weight, 0);
  const unitCount = 3 + Math.floor(Math.random() * 3);
  const counts = /* @__PURE__ */ new Map();
  for (let i = 0; i < unitCount; i++) {
    let roll = Math.random() * totalWeight;
    for (const { type, weight } of pool) {
      roll -= weight;
      if (roll <= 0) {
        counts.set(type, (counts.get(type) ?? 0) + 1);
        break;
      }
    }
  }
  return Array.from(counts.entries()).map(([type, count]) => ({ type, count }));
}
function createArmy(team, composition) {
  const comp = composition ?? ARMY_COMPOSITION;
  const units = [];
  const isBlue = team === "blue";
  const baseY = isBlue ? MAP_HEIGHT * 0.92 : MAP_HEIGHT * 0.08;
  const totalUnits = comp.reduce((sum, c) => sum + c.count, 0);
  const spacing = 60;
  const groupWidth = spacing * (totalUnits - 1);
  const startX = (MAP_WIDTH - groupWidth) / 2;
  let index = 0;
  for (const { type, count } of comp) {
    for (let i = 0; i < count; i++) {
      const x = startX + spacing * index;
      const pos = { x, y: baseY };
      units.push(createUnit(`${team}_${type}_${i}`, type, team, pos));
      index++;
    }
  }
  return units;
}
function createCtfArmy(team, blocks) {
  const units = [];
  const isBlue = team === "blue";
  const composition = CTF_ARMY_COMPOSITION;
  const totalUnits = composition.reduce((sum, c) => sum + c.count, 0);
  const spacing = 60;
  const groupWidth = spacing * (totalUnits - 1);
  const startX = (MAP_WIDTH - groupWidth) / 2;
  const baseY = isBlue ? MAP_HEIGHT - CTF_BASE_ZONE_WIDTH / 2 : CTF_BASE_ZONE_WIDTH / 2;
  let index = 0;
  for (const { type, count } of composition) {
    for (let i = 0; i < count; i++) {
      const x = startX + spacing * index;
      let pos = { x, y: baseY };
      pos = nudgeOutOfBlocks(pos, blocks);
      units.push(createUnit(`${team}_${type}_${i}`, type, team, pos));
      index++;
    }
  }
  for (const u of units) {
    u.gunAngle = isBlue ? -Math.PI / 2 : Math.PI / 2;
  }
  return units;
}
function createMissionArmy(team, composition, blocks) {
  const units = [];
  const isBlue = team === "blue";
  const totalUnits = composition.reduce((sum, c) => sum + c.count, 0);
  const spacing = 60;
  if (isBlue) {
    const baseY = MAP_HEIGHT * 0.92;
    const groupWidth = spacing * (totalUnits - 1);
    const startX = (MAP_WIDTH - groupWidth) / 2;
    let index = 0;
    for (const { type, count } of composition) {
      for (let i = 0; i < count; i++) {
        const x = startX + spacing * index;
        units.push(createUnit(`${team}_${type}_${i}`, type, team, { x, y: baseY }));
        index++;
      }
    }
  } else {
    const margin = 80;
    const xRange = MAP_WIDTH - margin * 2;
    const yMin = MAP_HEIGHT * 0.02;
    const yMax = MAP_HEIGHT * 0.25;
    const cols = Math.min(totalUnits, Math.ceil(Math.sqrt(totalUnits * 2)));
    const rows = Math.ceil(totalUnits / cols);
    const xStep = xRange / Math.max(cols, 1);
    const yStep = (yMax - yMin) / Math.max(rows, 1);
    let index = 0;
    for (const { type, count } of composition) {
      for (let i = 0; i < count; i++) {
        const row = Math.floor(index / cols);
        const col = index % cols;
        const stagger = row % 2 === 1 ? xStep * 0.5 : 0;
        const x = margin + xStep * 0.5 + col * xStep + stagger;
        const y = yMin + yStep * 0.5 + row * yStep;
        units.push(createUnit(`${team}_${type}_${i}`, type, team, {
          x: Math.min(x, MAP_WIDTH - margin),
          y
        }));
        index++;
      }
    }
  }
  if (blocks) {
    for (const u of units) {
      u.pos = nudgeOutOfBlocks(u.pos, blocks);
    }
  }
  return units;
}
function updateGunAngle(unit, desiredAngle, dt) {
  let diff = desiredAngle - unit.gunAngle;
  diff = (diff + Math.PI) % (2 * Math.PI) - Math.PI;
  if (diff < -Math.PI) diff += 2 * Math.PI;
  const maxStep = unit.turnSpeed * dt;
  if (Math.abs(diff) <= maxStep) {
    unit.gunAngle = desiredAngle;
  } else {
    unit.gunAngle += Math.sign(diff) * maxStep;
  }
  unit.gunAngle = (unit.gunAngle + Math.PI) % (2 * Math.PI) - Math.PI;
  if (unit.gunAngle < -Math.PI) unit.gunAngle += 2 * Math.PI;
}
function advanceWaypoint(unit, dt = 0) {
  if (!unit.alive) return;
  const atTarget = !unit.moveTarget || Math.abs(unit.pos.x - unit.moveTarget.x) < 2 && Math.abs(unit.pos.y - unit.moveTarget.y) < 2;
  if (unit.moveTarget && dt > 0) {
    const toTargetX = unit.moveTarget.x - unit.pos.x;
    const toTargetY = unit.moveTarget.y - unit.pos.y;
    const toTargetDist = Math.sqrt(toTargetX * toTargetX + toTargetY * toTargetY);
    const progress = toTargetDist > 1 ? (unit.vel.x * toTargetX + unit.vel.y * toTargetY) / toTargetDist : 0;
    if (progress < unit.speed * 0.1) {
      unit.stuckTime = (unit.stuckTime ?? 0) + dt;
    } else {
      unit.stuckTime = 0;
    }
  }
  const stuck = unit.moveTarget && (unit.stuckTime ?? 0) > 0.25;
  if (atTarget || stuck) {
    unit.stuckTime = 0;
    unit.moveTarget = unit.waypoints.length > 0 ? unit.waypoints.shift() : null;
  }
}
function distance(a, b) {
  const dx = a.x - b.x;
  const dy = a.y - b.y;
  return Math.sqrt(dx * dx + dy * dy);
}
function clamp(val, min, max) {
  return Math.max(min, Math.min(max, val));
}
function rectContainsCircle(obs, pos, radius) {
  const closestX = clamp(pos.x, obs.x, obs.x + obs.w);
  const closestY = clamp(pos.y, obs.y, obs.y + obs.h);
  const dx = pos.x - closestX;
  const dy = pos.y - closestY;
  return dx * dx + dy * dy < radius * radius;
}
function pushOutOfObstacles(pos, radius, obstacles) {
  for (let pass = 0; pass < 3; pass++) {
    let pushed = false;
    for (const obs of obstacles) {
      const closestX = clamp(pos.x, obs.x, obs.x + obs.w);
      const closestY = clamp(pos.y, obs.y, obs.y + obs.h);
      const dx = pos.x - closestX;
      const dy = pos.y - closestY;
      const dist2 = dx * dx + dy * dy;
      if (dist2 < radius * radius && dist2 > 1e-3) {
        const dist3 = Math.sqrt(dist2);
        const push = radius - dist3 + 0.5;
        pos.x += dx / dist3 * push;
        pos.y += dy / dist3 * push;
        pushed = true;
      } else if (dist2 <= 1e-3) {
        const toLeft = pos.x - obs.x;
        const toRight = obs.x + obs.w - pos.x;
        const toTop = pos.y - obs.y;
        const toBottom = obs.y + obs.h - pos.y;
        const minDist = Math.min(toLeft, toRight, toTop, toBottom);
        if (minDist === toLeft) pos.x = obs.x - radius - 0.5;
        else if (minDist === toRight) pos.x = obs.x + obs.w + radius + 0.5;
        else if (minDist === toTop) pos.y = obs.y - radius - 0.5;
        else pos.y = obs.y + obs.h + radius + 0.5;
        pushed = true;
      }
    }
    if (!pushed) break;
  }
}
function moveUnit(unit, dt, obstacles, allUnits = [], rng) {
  if (unit.knockbackVel) {
    const kbSpeed = Math.sqrt(unit.knockbackVel.x ** 2 + unit.knockbackVel.y ** 2);
    if (kbSpeed > 5) {
      unit.pos.x += unit.knockbackVel.x * dt;
      unit.pos.y += unit.knockbackVel.y * dt;
      unit.pos.x = clamp(unit.pos.x, unit.radius, MAP_WIDTH - unit.radius);
      unit.pos.y = clamp(unit.pos.y, unit.radius, MAP_HEIGHT - unit.radius);
      pushOutOfObstacles(unit.pos, unit.radius, obstacles);
      const decay = Math.exp(-8 * dt);
      unit.knockbackVel.x *= decay;
      unit.knockbackVel.y *= decay;
    } else {
      unit.knockbackVel = void 0;
    }
  }
  if (!unit.moveTarget || !unit.alive) {
    unit.vel = { x: 0, y: 0 };
    if (unit.type === "blade") unit.momentum = 0;
    return;
  }
  const dx = unit.moveTarget.x - unit.pos.x;
  const dy = unit.moveTarget.y - unit.pos.y;
  const dist2 = Math.sqrt(dx * dx + dy * dy);
  if (dist2 < 2) {
    unit.pos.x = unit.moveTarget.x;
    unit.pos.y = unit.moveTarget.y;
    unit.vel = { x: 0, y: 0 };
    if (unit.type === "blade") unit.momentum = 0;
    return;
  }
  let dirX = dx / dist2;
  let dirY = dy / dist2;
  if (unit.type === "blade") {
    const actualSpeed = Math.sqrt(unit.vel.x ** 2 + unit.vel.y ** 2);
    const forwardDot = actualSpeed > 1 ? unit.vel.x / actualSpeed * dirX + unit.vel.y / actualSpeed * dirY : 0;
    const effectiveSpeed = actualSpeed * Math.max(0, forwardDot);
    const prev = unit.momentum ?? 0;
    const rate = effectiveSpeed > prev ? 10 : 8;
    unit.momentum = prev + (effectiveSpeed - prev) * Math.min(1, rate * dt);
  }
  const BLADE_BASE_SPEED = 120;
  const speedMultiplier = unit.type === "blade" ? 1 + Math.min(1, (unit.momentum ?? 0) / BLADE_BASE_SPEED) : 1;
  const step = unit.speed * speedMultiplier * dt;
  const lookAhead = unit.radius * 5;
  let steerX = 0;
  let steerY = 0;
  for (const other of allUnits) {
    if (other === unit || !other.alive) continue;
    const ox = other.pos.x - unit.pos.x;
    const oy = other.pos.y - unit.pos.y;
    const oDist = Math.sqrt(ox * ox + oy * oy);
    const minSep = unit.radius + other.radius + 4;
    if (oDist >= lookAhead + other.radius || oDist < 0.01) continue;
    if (oDist < minSep * 1.5) {
      const pushStrength = (minSep * 1.5 - oDist) / (minSep * 1.5);
      steerX -= ox / oDist * pushStrength * 1.2;
      steerY -= oy / oDist * pushStrength * 1.2;
    }
    const dot = ox * dirX + oy * dirY;
    if (dot < 0) continue;
    const perpDist = Math.abs(-dirY * ox + dirX * oy);
    if (perpDist < minSep) {
      const side = -dirY * ox + dirX * oy;
      const steerDir = side >= 0 ? 1 : -1;
      const strength = (minSep - perpDist) / minSep;
      steerX += -dirY * steerDir * strength;
      steerY += dirX * steerDir * strength;
    }
  }
  const edgeMargin = unit.radius * 4;
  if (unit.pos.x < unit.radius + edgeMargin) {
    steerX += (unit.radius + edgeMargin - unit.pos.x) / edgeMargin;
  } else if (unit.pos.x > MAP_WIDTH - unit.radius - edgeMargin) {
    steerX -= (unit.pos.x - (MAP_WIDTH - unit.radius - edgeMargin)) / edgeMargin;
  }
  if (unit.pos.y < unit.radius + edgeMargin) {
    steerY += (unit.radius + edgeMargin - unit.pos.y) / edgeMargin;
  } else if (unit.pos.y > MAP_HEIGHT - unit.radius - edgeMargin) {
    steerY -= (unit.pos.y - (MAP_HEIGHT - unit.radius - edgeMargin)) / edgeMargin;
  }
  if (steerX !== 0 || steerY !== 0) {
    dirX += steerX * 0.8;
    dirY += steerY * 0.8;
    const len = Math.sqrt(dirX * dirX + dirY * dirY);
    if (len > 0.01) {
      dirX /= len;
      dirY /= len;
    }
  }
  if (unit.type === "zombie") {
    const wobble = ((rng ?? Math.random)() - 0.5) * 1.4;
    const ox = dirX;
    const oy = dirY;
    dirX += -oy * wobble;
    dirY += ox * wobble;
    const len = Math.sqrt(dirX * dirX + dirY * dirY);
    if (len > 0.01) {
      dirX /= len;
      dirY /= len;
    }
  }
  const moveX = dirX * Math.min(step, dist2);
  const moveY = dirY * Math.min(step, dist2);
  const oldX = unit.pos.x;
  const oldY = unit.pos.y;
  let newX = oldX + moveX;
  let newY = oldY + moveY;
  const blocked = obstacles.some((o) => rectContainsCircle(o, { x: newX, y: newY }, unit.radius));
  if (blocked) {
    const hOnly = !obstacles.some((o) => rectContainsCircle(o, { x: newX, y: oldY }, unit.radius));
    const vOnly = !obstacles.some((o) => rectContainsCircle(o, { x: oldX, y: newY }, unit.radius));
    if (hOnly) {
      newY = oldY;
    } else if (vOnly) {
      newX = oldX;
    } else {
      const stepLen = Math.sqrt(moveX * moveX + moveY * moveY);
      const baseAngle = Math.atan2(moveY, moveX);
      let escaped = false;
      for (const offset of [Math.PI / 6, -Math.PI / 6, Math.PI / 3, -Math.PI / 3, Math.PI / 2, -Math.PI / 2]) {
        const tryX = oldX + Math.cos(baseAngle + offset) * stepLen;
        const tryY = oldY + Math.sin(baseAngle + offset) * stepLen;
        if (!obstacles.some((o) => rectContainsCircle(o, { x: tryX, y: tryY }, unit.radius))) {
          newX = tryX;
          newY = tryY;
          escaped = true;
          break;
        }
      }
      if (!escaped) {
        pushOutOfObstacles(unit.pos, unit.radius, obstacles);
        unit.vel = { x: 0, y: 0 };
        return;
      }
    }
  }
  const hitsUnit = (px, py) => allUnits.some((other) => {
    if (other === unit || !other.alive) return false;
    const cdx = px - other.pos.x;
    const cdy = py - other.pos.y;
    const minR = unit.radius + other.radius;
    return cdx * cdx + cdy * cdy < minR * minR;
  });
  if (hitsUnit(newX, newY)) {
    if (!hitsUnit(newX, oldY)) {
      newY = oldY;
    } else if (!hitsUnit(oldX, newY)) {
      newX = oldX;
    } else {
      unit.vel = { x: 0, y: 0 };
      return;
    }
  }
  newX = clamp(newX, unit.radius, MAP_WIDTH - unit.radius);
  newY = clamp(newY, unit.radius, MAP_HEIGHT - unit.radius);
  unit.pos.x = newX;
  unit.pos.y = newY;
  pushOutOfObstacles(unit.pos, unit.radius, obstacles);
  unit.vel = dt > 0 ? { x: (newX - oldX) / dt, y: (newY - oldY) / dt } : { x: 0, y: 0 };
}
function separateUnits(units, obstacles = []) {
  const alive = units.filter((u) => u.alive);
  const ITERATIONS = 5;
  for (let iter = 0; iter < ITERATIONS; iter++) {
    for (let i = 0; i < alive.length; i++) {
      for (let j = i + 1; j < alive.length; j++) {
        const a = alive[i];
        const b = alive[j];
        const dx = b.pos.x - a.pos.x;
        const dy = b.pos.y - a.pos.y;
        const dist2 = Math.sqrt(dx * dx + dy * dy);
        const minDist = a.radius + b.radius + 1;
        if (dist2 < minDist && dist2 > 0.01) {
          const overlap = (minDist - dist2) / 2;
          const nx = dx / dist2;
          const ny = dy / dist2;
          const aNewX = a.pos.x - nx * overlap;
          const aNewY = a.pos.y - ny * overlap;
          const bNewX = b.pos.x + nx * overlap;
          const bNewY = b.pos.y + ny * overlap;
          const aBlocked = obstacles.some((o) => rectContainsCircle(o, { x: aNewX, y: aNewY }, a.radius));
          const bBlocked = obstacles.some((o) => rectContainsCircle(o, { x: bNewX, y: bNewY }, b.radius));
          if (!aBlocked && !bBlocked) {
            a.pos.x = aNewX;
            a.pos.y = aNewY;
            b.pos.x = bNewX;
            b.pos.y = bNewY;
          } else if (!bBlocked) {
            b.pos.x += nx * overlap * 2;
            b.pos.y += ny * overlap * 2;
          } else if (!aBlocked) {
            a.pos.x -= nx * overlap * 2;
            a.pos.y -= ny * overlap * 2;
          }
          const relVelDot = (a.vel.x - b.vel.x) * nx + (a.vel.y - b.vel.y) * ny;
          if (relVelDot < 0) {
            const bounce = a.team === b.team ? 0.5 : 0.3;
            a.vel.x -= nx * relVelDot * (0.5 + bounce);
            a.vel.y -= ny * relVelDot * (0.5 + bounce);
            b.vel.x += nx * relVelDot * (0.5 + bounce);
            b.vel.y += ny * relVelDot * (0.5 + bounce);
          }
          a.pos.x = clamp(a.pos.x, a.radius, MAP_WIDTH - a.radius);
          a.pos.y = clamp(a.pos.y, a.radius, MAP_HEIGHT - a.radius);
          b.pos.x = clamp(b.pos.x, b.radius, MAP_WIDTH - b.radius);
          b.pos.y = clamp(b.pos.y, b.radius, MAP_HEIGHT - b.radius);
        } else if (dist2 <= 0.01) {
          a.pos.x -= 1;
          a.pos.y -= 1;
          b.pos.x += 1;
          b.pos.y += 1;
        }
      }
    }
  }
  for (const unit of alive) {
    pushOutOfObstacles(unit.pos, unit.radius, obstacles);
    unit.pos.x = clamp(unit.pos.x, unit.radius, MAP_WIDTH - unit.radius);
    unit.pos.y = clamp(unit.pos.y, unit.radius, MAP_HEIGHT - unit.radius);
  }
}
function hasLineOfSight(a, b, obstacles, padding = 0) {
  return !obstacles.some((o) => segmentHitsRect(a, b, o, padding));
}
function findTarget(attacker, allUnits, preferredId, obstacles = []) {
  const enemies = allUnits.filter((u) => u.alive && u.team !== attacker.team);
  if (enemies.length === 0) return null;
  if (preferredId) {
    const preferred = enemies.find((u) => u.id === preferredId);
    if (preferred && hasLineOfSight(attacker.pos, preferred.pos, obstacles)) return preferred;
  }
  let nearestVisible = null;
  let nearestVisibleDist = Infinity;
  let nearestAny = null;
  let nearestAnyDist = Infinity;
  for (const enemy of enemies) {
    const d = distance(attacker.pos, enemy.pos);
    if (d < nearestAnyDist) {
      nearestAny = enemy;
      nearestAnyDist = d;
    }
    if (hasLineOfSight(attacker.pos, enemy.pos, obstacles) && d < nearestVisibleDist) {
      nearestVisible = enemy;
      nearestVisibleDist = d;
    }
  }
  return nearestVisible ?? nearestAny;
}
function getElevationLevel(pos, zones) {
  let level = 0;
  for (const z of zones) {
    if (pos.x >= z.x && pos.x <= z.x + z.w && pos.y >= z.y && pos.y <= z.y + z.h) {
      level++;
    }
  }
  return level;
}
function isInRange(attacker, target, elevationZones = []) {
  const level = getElevationLevel(attacker.pos, elevationZones);
  const bonus = attacker.type === "blade" ? 0 : ELEVATION_RANGE_BONUS;
  const range = attacker.range * (1 + bonus * level);
  return distance(attacker.pos, target.pos) <= range + attacker.radius + target.radius;
}
function isFlanked(projectileVelAngle, targetGunAngle) {
  const incomingAngle = projectileVelAngle + Math.PI;
  let diff = incomingAngle - targetGunAngle;
  diff = (diff + Math.PI) % (2 * Math.PI) - Math.PI;
  if (diff < -Math.PI) diff += 2 * Math.PI;
  return Math.abs(diff) > FLANK_ANGLE_THRESHOLD;
}
function applyDamage(unit, amount) {
  const reduced = unit.damageReduction ? amount * (1 - unit.damageReduction) : amount;
  unit.hp = Math.max(0, unit.hp - reduced);
  if (unit.hp === 0) {
    unit.alive = false;
  }
}
function bladeAoeAttack(unit, units, dt) {
  if (unit.type !== "blade" || !unit.alive) return [];
  unit.fireTimer -= dt;
  if (unit.fireTimer > 0) return [];
  unit.fireTimer = unit.fireCooldown;
  const hits = [];
  const BLADE_BASE_SPEED = 120;
  const speedRatio = Math.min(1, (unit.momentum ?? 0) / BLADE_BASE_SPEED);
  const damageFactor = 0.3 + speedRatio * 2.2;
  const scaledDamage = Math.round(unit.damage * damageFactor);
  const knockback = 20 + speedRatio * 80;
  for (const enemy of units) {
    if (!enemy.alive || enemy.team === unit.team) continue;
    const dx = enemy.pos.x - unit.pos.x;
    const dy = enemy.pos.y - unit.pos.y;
    const dist2 = Math.sqrt(dx * dx + dy * dy);
    const hitRange = unit.range + unit.radius + enemy.radius;
    if (dist2 <= hitRange) {
      const wasBefore = enemy.hp;
      applyDamage(enemy, scaledDamage);
      hits.push({
        pos: { x: enemy.pos.x, y: enemy.pos.y },
        targetId: enemy.id,
        killed: wasBefore > 0 && !enemy.alive,
        team: unit.team,
        damage: scaledDamage
      });
      if (dist2 > 0) {
        const kbSpeed = knockback / 0.15;
        enemy.knockbackVel = {
          x: dx / dist2 * kbSpeed,
          y: dy / dist2 * kbSpeed
        };
        const selfKbSpeed = (20 + speedRatio * 60) / 0.15;
        const velSpeed = Math.sqrt(unit.vel.x ** 2 + unit.vel.y ** 2);
        if (velSpeed > 1) {
          const recoilX = -(unit.vel.x / velSpeed) * selfKbSpeed;
          const recoilY = -(unit.vel.y / velSpeed) * selfKbSpeed;
          unit.knockbackVel = {
            x: (unit.knockbackVel?.x ?? 0) + recoilX,
            y: (unit.knockbackVel?.y ?? 0) + recoilY
          };
        }
      }
    }
  }
  return hits;
}
function bomberExplode(bomber, allUnits) {
  const EXPLOSION_RADIUS = 80;
  const EXPLOSION_DAMAGE = 40;
  const hits = [];
  for (const u of allUnits) {
    if (!u.alive || u.id === bomber.id) continue;
    const dx = u.pos.x - bomber.pos.x;
    const dy = u.pos.y - bomber.pos.y;
    const dist2 = Math.sqrt(dx * dx + dy * dy);
    if (dist2 <= EXPLOSION_RADIUS + u.radius) {
      const before = u.hp;
      applyDamage(u, EXPLOSION_DAMAGE);
      hits.push({
        pos: { x: u.pos.x, y: u.pos.y },
        targetId: u.id,
        killed: before > 0 && !u.alive,
        damage: EXPLOSION_DAMAGE
      });
    }
  }
  for (const hit of [...hits]) {
    if (hit.killed) {
      const deadUnit = allUnits.find((u) => u.id === hit.targetId);
      if (deadUnit && deadUnit.type === "bomber") {
        const chainHits = bomberExplode(deadUnit, allUnits);
        hits.push(...chainHits);
      }
    }
  }
  return hits;
}
function tryFireProjectile(unit, target, dt, elevationZones = []) {
  unit.fireTimer -= dt;
  if (unit.fireTimer > 0) return [];
  const aimAngle = Math.atan2(target.pos.y - unit.pos.y, target.pos.x - unit.pos.x);
  let aimDiff = aimAngle - unit.gunAngle;
  aimDiff = (aimDiff + Math.PI) % (2 * Math.PI) - Math.PI;
  if (aimDiff < -Math.PI) aimDiff += 2 * Math.PI;
  if (Math.abs(aimDiff) > 0.15) return [];
  unit.fireTimer = unit.fireCooldown;
  let predictedX = target.pos.x;
  let predictedY = target.pos.y;
  for (let iter = 0; iter < 2; iter++) {
    const pdx2 = predictedX - unit.pos.x;
    const pdy2 = predictedY - unit.pos.y;
    const pdist2 = Math.sqrt(pdx2 * pdx2 + pdy2 * pdy2);
    const flightTime = pdist2 / unit.projectileSpeed;
    predictedX = target.pos.x + target.vel.x * flightTime;
    predictedY = target.pos.y + target.vel.y * flightTime;
  }
  if (unit.type === "blade" || unit.type === "bomber") return [];
  const pdx = predictedX - unit.pos.x;
  const pdy = predictedY - unit.pos.y;
  const pdist = Math.sqrt(pdx * pdx + pdy * pdy);
  if (pdist < 1) return [];
  const maxRange = unit.range * (1 + ELEVATION_RANGE_BONUS * getElevationLevel(unit.pos, elevationZones)) + unit.radius + 40;
  return [{
    pos: { x: unit.pos.x, y: unit.pos.y },
    vel: { x: pdx / pdist * unit.projectileSpeed, y: pdy / pdist * unit.projectileSpeed },
    target: { x: predictedX, y: predictedY },
    damage: unit.damage,
    radius: unit.projectileRadius,
    team: unit.team,
    maxRange,
    distanceTraveled: 0,
    piercing: unit.piercing ?? unit.type === "sniper"
  }];
}
function updateProjectiles(projectiles, units, dt, obstacles = []) {
  const alive = [];
  const hits = [];
  for (const p of projectiles) {
    const oldPos = { x: p.pos.x, y: p.pos.y };
    const moveX = p.vel.x * dt;
    const moveY = p.vel.y * dt;
    p.pos.x += moveX;
    p.pos.y += moveY;
    p.distanceTraveled += Math.sqrt(moveX * moveX + moveY * moveY);
    if (!p.trail) p.trail = [];
    p.trail.push({ x: p.pos.x, y: p.pos.y });
    if (p.trail.length > 5) p.trail.shift();
    if (p.pos.x < 0 || p.pos.x > MAP_WIDTH || p.pos.y < 0 || p.pos.y > MAP_HEIGHT) continue;
    if (p.distanceTraveled > p.maxRange) continue;
    if (obstacles.some((o) => segmentHitsRect(oldPos, p.pos, o, p.radius))) continue;
    let consumed = false;
    for (const unit of units) {
      if (!unit.alive || unit.team === p.team) continue;
      if (p.piercing && p.hitIds?.has(unit.id)) continue;
      const dx = p.pos.x - unit.pos.x;
      const dy = p.pos.y - unit.pos.y;
      const hitDist = p.radius + unit.radius * COLLISION_HITBOX_SCALE;
      if (dx * dx + dy * dy <= hitDist * hitDist) {
        const projAngle = Math.atan2(p.vel.y, p.vel.x);
        if (unit.type === "shielder" && (unit.shieldHits ?? 0) < SHIELD_MAX_HITS) {
          if (!isFlanked(projAngle, unit.gunAngle)) {
            unit.shieldHits = (unit.shieldHits ?? 0) + 1;
            if (!p.piercing) {
              consumed = true;
              break;
            }
            continue;
          }
        }
        const flanked = isFlanked(projAngle, unit.gunAngle);
        let actualDamage = flanked ? p.damage * FLANK_DAMAGE_MULTIPLIER : p.damage;
        const knockback = p.knockback ?? p.damage * 0.4;
        const projSpeed = Math.sqrt(p.vel.x * p.vel.x + p.vel.y * p.vel.y);
        if (projSpeed > 0 && knockback > 0) {
          const kbSpeed = knockback / 0.15;
          unit.knockbackVel = {
            x: p.vel.x / projSpeed * kbSpeed,
            y: p.vel.y / projSpeed * kbSpeed
          };
        }
        const wasBefore = unit.hp;
        applyDamage(unit, actualDamage);
        hits.push({
          pos: { x: p.pos.x, y: p.pos.y },
          targetId: unit.id,
          killed: wasBefore > 0 && !unit.alive,
          team: p.team,
          angle: projAngle,
          flanked,
          damage: actualDamage
        });
        if (p.piercing) {
          if (!p.hitIds) p.hitIds = /* @__PURE__ */ new Set();
          p.hitIds.add(unit.id);
          p.damage *= 0.5;
        } else {
          consumed = true;
          break;
        }
      }
    }
    if (!consumed) alive.push(p);
  }
  return { alive, hits };
}

// src/battlefield.ts
function randomInRange(min, max) {
  return Math.floor(Math.random() * (max - min)) + min;
}
function generateObstacles() {
  const obstacles = [];
  const pairCount = randomInRange(1, 2);
  const hasCenter = Math.random() > 0.5;
  for (let i = 0; i < pairCount; i++) {
    const w = randomInRange(30, 60);
    const h = randomInRange(30, 60);
    const x = randomInRange(50, MAP_WIDTH - 50 - w);
    const y = randomInRange(MAP_HEIGHT * 0.25, MAP_HEIGHT * 0.45 - h);
    obstacles.push({ x, y, w, h });
    obstacles.push({ x, y: MAP_HEIGHT - y - h, w, h });
  }
  if (hasCenter || obstacles.length < 3) {
    const w = randomInRange(30, 60);
    const h = randomInRange(30, 60);
    const x = randomInRange(50, MAP_WIDTH - 50 - w);
    const y = (MAP_HEIGHT - h) / 2;
    obstacles.push({ x, y, w, h });
  }
  return obstacles;
}
function generateElevationZones() {
  const zones = [];
  const pairCount = randomInRange(1, 3);
  for (let i = 0; i < pairCount; i++) {
    const w = randomInRange(80, 160);
    const h = randomInRange(60, 120);
    const x = randomInRange(50, MAP_WIDTH - 50 - w);
    const y = randomInRange(MAP_HEIGHT * 0.25, MAP_HEIGHT * 0.45 - h);
    zones.push({ x, y, w, h });
    zones.push({ x, y: MAP_HEIGHT - y - h, w, h });
  }
  return zones;
}
function generateCtfObstacles() {
  const obstacles = [];
  const pairCount = randomInRange(2, 4);
  const safeZone = CTF_BASE_ZONE_WIDTH + 20;
  for (let i = 0; i < pairCount; i++) {
    const w = randomInRange(30, 60);
    const h = randomInRange(30, 60);
    const x = randomInRange(MAP_WIDTH * 0.15, MAP_WIDTH * 0.85 - w);
    const y = randomInRange(safeZone, MAP_HEIGHT / 2 - h / 2);
    obstacles.push({ x, y, w, h });
    obstacles.push({ x, y: MAP_HEIGHT - y - h, w, h });
  }
  return obstacles;
}
function generateCtfElevationZones() {
  const zones = [];
  const pairCount = randomInRange(1, 3);
  const safeZone = CTF_BASE_ZONE_WIDTH + 10;
  for (let i = 0; i < pairCount; i++) {
    const w = randomInRange(80, 160);
    const h = randomInRange(60, 120);
    const x = randomInRange(MAP_WIDTH * 0.15, MAP_WIDTH * 0.85 - w);
    const y = randomInRange(safeZone, MAP_HEIGHT / 2 - h / 2);
    zones.push({ x, y, w, h });
    zones.push({ x, y: MAP_HEIGHT - y - h, w, h });
  }
  return zones;
}

// src/ctf.ts
function createCtfState() {
  const blueHome = { x: MAP_WIDTH / 2, y: MAP_HEIGHT - CTF_BASE_ZONE_WIDTH / 2 };
  const redHome = { x: MAP_WIDTH / 2, y: CTF_BASE_ZONE_WIDTH / 2 };
  return {
    blueFlag: { team: "blue", pos: { ...blueHome }, homePos: { ...blueHome }, carrierId: null, dropped: false },
    redFlag: { team: "red", pos: { ...redHome }, homePos: { ...redHome }, carrierId: null, dropped: false },
    winner: null
  };
}
function dist(a, b) {
  const dx = a.x - b.x;
  const dy = a.y - b.y;
  return Math.sqrt(dx * dx + dy * dy);
}
function updateFlag(flag, units) {
  if (flag.carrierId) {
    const carrier = units.find((u) => u.id === flag.carrierId);
    if (!carrier || !carrier.alive) {
      flag.carrierId = null;
      flag.dropped = true;
      return;
    }
    flag.pos = { x: carrier.pos.x, y: carrier.pos.y };
    return;
  }
  for (const unit of units) {
    if (!unit.alive) continue;
    if (dist(unit.pos, flag.pos) > CTF_FLAG_PICKUP_RADIUS) continue;
    if (unit.team === flag.team) {
      if (flag.dropped) {
        flag.pos = { ...flag.homePos };
        flag.dropped = false;
      }
    } else {
      flag.carrierId = unit.id;
      flag.dropped = false;
      return;
    }
  }
}
function updateCtfFlags(state, units) {
  updateFlag(state.blueFlag, units);
  updateFlag(state.redFlag, units);
}
function isFlagAtHome(flag) {
  return !flag.carrierId && !flag.dropped;
}
function checkCtfCapture(state) {
  if (state.blueFlag.carrierId && state.blueFlag.pos.y < CTF_BASE_ZONE_WIDTH && isFlagAtHome(state.redFlag)) {
    return "red";
  }
  if (state.redFlag.carrierId && state.redFlag.pos.y > MAP_HEIGHT - CTF_BASE_ZONE_WIDTH && isFlagAtHome(state.blueFlag)) {
    return "blue";
  }
  return null;
}

// src/ai-scoring.ts
var WEIGHTS = {
  sniper: { distIdeal: [180, 300], distPenaltyScale: 0.15, los: 30, elevation: 25, cover: 20, flank: 5 },
  blade: { distIdeal: [0, 40], distPenaltyScale: 0.25, los: 15, elevation: 5, cover: 5, flank: 15 },
  soldier: { distIdeal: [50, 120], distPenaltyScale: 0.15, los: 20, elevation: 15, cover: 15, flank: 25 },
  zombie: { distIdeal: [0, 30], distPenaltyScale: 0.1, los: 5, elevation: 0, cover: 0, flank: 5 },
  shielder: { distIdeal: [0, 30], distPenaltyScale: 0.3, los: 5, elevation: 0, cover: 5, flank: 5 },
  bomber: { distIdeal: [0, 20], distPenaltyScale: 0.3, los: 5, elevation: 0, cover: 0, flank: 0 }
};
function scorePosition(ctx) {
  const { candidate, unit, enemies, obstacles, elevationZones } = ctx;
  const w = WEIGHTS[unit.type];
  const dx = candidate.x - unit.pos.x;
  const dy = candidate.y - unit.pos.y;
  const dist2 = Math.sqrt(dx * dx + dy * dy);
  const maxDist = unit.speed * ROUND_DURATION_S;
  if (dist2 > maxDist) return -Infinity;
  let score = 0;
  let nearestEnemy = null;
  let nearestDist = Infinity;
  for (const e of enemies) {
    const ex = candidate.x - e.pos.x;
    const ey = candidate.y - e.pos.y;
    const eDist = Math.sqrt(ex * ex + ey * ey);
    if (eDist < nearestDist) {
      nearestDist = eDist;
      nearestEnemy = e;
    }
  }
  if (nearestEnemy) {
    const [idealMin, idealMax] = w.distIdeal;
    if (nearestDist < idealMin) {
      score -= (idealMin - nearestDist) * w.distPenaltyScale;
    } else if (nearestDist > idealMax) {
      score -= (nearestDist - idealMax) * w.distPenaltyScale;
    }
    if (hasLineOfSight(candidate, nearestEnemy.pos, obstacles)) {
      score += w.los;
    }
    score += flankScore(candidate, nearestEnemy.pos, nearestEnemy.gunAngle) * w.flank;
  }
  const elevLevel = getElevationLevel(candidate, elevationZones);
  score += elevLevel * w.elevation;
  if (ctx.ctfState) {
    const ctf = ctx.ctfState;
    const enemyFlag = unit.team === "blue" ? ctf.redFlag : ctf.blueFlag;
    const ownFlag = unit.team === "blue" ? ctf.blueFlag : ctf.redFlag;
    const isCarrier = enemyFlag.carrierId === unit.id;
    const teamHasCarrier = enemyFlag.carrierId !== null;
    const enemyHasOurFlag = ownFlag.carrierId !== null;
    if (isCarrier) {
      const homeY = unit.team === "blue" ? MAP_HEIGHT - CTF_BASE_ZONE_WIDTH / 2 : CTF_BASE_ZONE_WIDTH / 2;
      const distToHome = Math.abs(candidate.y - homeY);
      score += (MAP_HEIGHT - distToHome) / MAP_HEIGHT * 40;
    } else if (enemyHasOurFlag) {
      const carrierDist = Math.sqrt(
        (candidate.x - ownFlag.pos.x) ** 2 + (candidate.y - ownFlag.pos.y) ** 2
      );
      score += (MAP_WIDTH - Math.min(carrierDist, MAP_WIDTH)) / MAP_WIDTH * 35;
    } else if (teamHasCarrier) {
      const flagDist = Math.sqrt(
        (candidate.x - enemyFlag.pos.x) ** 2 + (candidate.y - enemyFlag.pos.y) ** 2
      );
      score += Math.max(0, 15 - flagDist / 20);
    } else {
      const flagDist = Math.sqrt(
        (candidate.x - enemyFlag.pos.x) ** 2 + (candidate.y - enemyFlag.pos.y) ** 2
      );
      score += (MAP_WIDTH - Math.min(flagDist, MAP_WIDTH)) / MAP_WIDTH * 20;
    }
    const ownFlagDist = Math.sqrt(
      (candidate.x - ownFlag.homePos.x) ** 2 + (candidate.y - ownFlag.homePos.y) ** 2
    );
    if (ownFlagDist < 200) {
      score += 8;
    }
  }
  return score;
}
function generateCandidates(unit, obstacles, elevationZones) {
  const maxDist = unit.speed * ROUND_DURATION_S;
  const padding = unit.radius + 4;
  const candidates = [];
  const gridStep = 50;
  const minX = Math.max(padding, unit.pos.x - maxDist);
  const maxX = Math.min(MAP_WIDTH - padding, unit.pos.x + maxDist);
  const minY = Math.max(padding, unit.pos.y - maxDist);
  const maxY = Math.min(MAP_HEIGHT - padding, unit.pos.y + maxDist);
  for (let x = minX; x <= maxX; x += gridStep) {
    for (let y = minY; y <= maxY; y += gridStep) {
      const pos = { x, y };
      if (!isInsideObstacle(pos, obstacles, padding)) {
        candidates.push(pos);
      }
    }
  }
  for (const zone of elevationZones) {
    const center = { x: zone.x + zone.w / 2, y: zone.y + zone.h / 2 };
    if (!isInsideObstacle(center, obstacles, padding)) {
      candidates.push(center);
    }
  }
  return candidates;
}
function isInsideObstacle(pos, obstacles, padding) {
  return obstacles.some((obs) => {
    const cx = Math.max(obs.x, Math.min(obs.x + obs.w, pos.x));
    const cy = Math.max(obs.y, Math.min(obs.y + obs.h, pos.y));
    const dx = pos.x - cx;
    const dy = pos.y - cy;
    return dx * dx + dy * dy < padding * padding;
  });
}

// src/rng.ts
function createRng(seed) {
  let s = seed | 0;
  return () => {
    s = s + 1831565813 | 0;
    let t = Math.imul(s ^ s >>> 15, 1 | s);
    t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}

// src/game.ts
var FIXED_DT = 1 / 60;
var GameEngine = class _GameEngine {
  units = [];
  obstacles = [];
  elevationZones = [];
  projectiles = [];
  renderer;
  running = false;
  speedMultiplier = 1;
  elapsedTime = 0;
  roundTimer = 0;
  onEvent;
  pathDrawer = null;
  _phase = "blue-planning";
  roundNumber = 1;
  aiMode = false;
  idleTime = 0;
  endingBattle = false;
  endDelayTimer = 0;
  pendingWinner = null;
  hordeMode = false;
  hordeStartDelay = 0;
  hordeBlueUnits = null;
  hordeRedArmy = null;
  hordeMap = null;
  ctfMode = false;
  ctfState = null;
  replayFrames = [];
  replayEvents = [];
  onlineHostMode = false;
  onPhaseChangeCallback;
  accumulator = 0;
  simulationTick = 0;
  rng = Math.random;
  seed = 0;
  lockstepMode = false;
  constructor(renderer, onEvent, opts) {
    this.renderer = renderer;
    this.onEvent = onEvent;
    this.aiMode = opts?.aiMode ?? false;
    this.seed = opts?.seed ?? Math.random() * 2147483647 | 0;
    this.hordeMode = opts?.horde ?? false;
    this.hordeBlueUnits = opts?.hordeBlueUnits ?? null;
    this.hordeRedArmy = opts?.hordeRedArmy ?? null;
    this.hordeMap = opts?.hordeMap ?? null;
    this.ctfMode = opts?.ctfMode ?? false;
    this.onlineHostMode = opts?.onlineHost ?? false;
    this.onPhaseChangeCallback = opts?.onPhaseChange;
  }
  get phase() {
    return this._phase;
  }
  getSeed() {
    return this.seed;
  }
  /** The effective PRNG seed for the current round (base seed + round number).
   *  This is the exact value passed to createRng() when a round starts, so it's
   *  what the host must transmit to the guest for lockstep determinism. */
  getRoundSeed() {
    return this.seed + this.roundNumber;
  }
  startBattle() {
    if (this.ctfMode) {
      this.obstacles = generateCtfObstacles();
      this.elevationZones = generateCtfElevationZones();
      this.units = [...createCtfArmy("blue", this.obstacles), ...createCtfArmy("red", this.obstacles)];
      this.ctfState = createCtfState();
    } else if (this.hordeMap) {
      this.obstacles = this.hordeMap.obstacles;
      this.elevationZones = this.hordeMap.elevationZones;
    } else {
      this.obstacles = generateObstacles();
      this.elevationZones = generateElevationZones();
    }
    const allBlocks = this.obstacles;
    if (!this.ctfMode) {
      if (this.hordeMode && this.hordeBlueUnits && this.hordeRedArmy) {
        const redUnits = createMissionArmy("red", this.hordeRedArmy, allBlocks);
        const waveTag = `w${Date.now() % 1e4}`;
        for (const u of redUnits) {
          u.id = u.id.replace("red_", `red_${waveTag}_`);
        }
        this.units = [...this.hordeBlueUnits, ...redUnits];
      } else {
        const composition = generateRandomComposition();
        this.units = [...createArmy("blue", composition), ...createArmy("red", composition)];
      }
    }
    this.projectiles = [];
    this.elapsedTime = 0;
    this.roundTimer = 0;
    this.running = true;
    if (this.renderer) {
      this.pathDrawer = this.renderer.createPathDrawer((pos) => this.renderer.highlightZonesAt(pos));
      this.renderer.renderElevationZones(this.elevationZones);
      this.renderer.renderObstacles(this.obstacles);
      if (this.ctfMode) {
        this.renderer.renderBaseZones();
      }
      this.renderer.renderUnits(this.units);
      this.renderer.ticker.add(this.tick, this);
    }
    this.setPhase("blue-planning");
  }
  coverTimeout = null;
  /** Called by the UI "Done" button to end the current planning phase. */
  confirmPlan() {
    if (this._phase === "blue-planning") {
      this.setPhase("cover");
      if (!this.aiMode) {
        this.coverTimeout = setTimeout(() => {
          this.skipCover();
        }, COVER_SCREEN_DURATION_MS);
      }
    } else if (this._phase === "red-planning") {
      this.setPhase("playing");
    }
  }
  /** Skip the cover screen early (e.g. on tap). */
  skipCover() {
    if (this._phase !== "cover") return;
    if (this.coverTimeout) {
      clearTimeout(this.coverTimeout);
      this.coverTimeout = null;
    }
    this.setPhase("red-planning");
  }
  setPhase(phase) {
    this._phase = phase;
    if (phase === "blue-planning") {
      this.pathDrawer?.clearPaths("blue");
      if (this.hordeMode) this.generateAiPaths();
      this.pathDrawer?.enable("blue", this.units, this.elevationZones);
    } else if (phase === "cover") {
      this.pathDrawer?.disable();
      if (this.onlineHostMode) {
        this.onEvent("phase-change", { phase, round: this.roundNumber });
        this.setPhase("red-planning");
        return;
      }
      if (this.aiMode) {
        if (!this.hordeMode) {
          this.generateAiPaths();
        }
        this.onEvent("phase-change", { phase, round: this.roundNumber });
        this.setPhase("playing");
        return;
      }
    } else if (phase === "red-planning") {
      if (!this.onlineHostMode) {
        this.pathDrawer?.clearPaths("red");
        this.pathDrawer?.enable("red", this.units, this.elevationZones);
      }
    } else if (phase === "playing") {
      this.pathDrawer?.disable();
      this.pathDrawer?.clearGraphics();
      this.roundTimer = ROUND_DURATION_S;
      this.idleTime = 0;
      this.accumulator = 0;
      this.simulationTick = 0;
      this.rng = createRng(this.seed + this.roundNumber);
      this.renderer?.effects?.addRoundStartFlash(MAP_WIDTH, MAP_HEIGHT);
    }
    this.onEvent("phase-change", { phase, round: this.roundNumber });
    this.onPhaseChangeCallback?.(phase);
  }
  /** Generate AI paths for red units using position-scoring system. */
  generateAiPaths() {
    const allBlockers = this.obstacles;
    const redUnits = this.units.filter((u) => u.alive && u.team === "red");
    const enemies = this.units.filter((u) => u.alive && u.team === "blue");
    if (redUnits.length === 0) return;
    const candidates = generateCandidates(
      redUnits[0],
      this.obstacles,
      this.elevationZones
    );
    for (const unit of redUnits) {
      if (unit.type === "zombie" || unit.type === "shielder" || unit.type === "bomber") continue;
      const margin = 8;
      const padding = unit.radius + margin;
      const scored = [];
      for (const candidate of candidates) {
        const s = scorePosition({
          candidate,
          unit,
          enemies,
          obstacles: this.obstacles,
          elevationZones: this.elevationZones,
          ctfState: this.ctfState ?? void 0
        });
        scored.push({ pos: candidate, score: s });
      }
      scored.sort((a, b) => b.score - a.score);
      let bestPos = unit.pos;
      let bestWaypoints = [];
      for (const { pos: candidate, score } of scored) {
        if (score === -Infinity) break;
        const detours = detourWaypoints(unit.pos, candidate, allBlockers, padding);
        const chain = [...detours, candidate];
        let pathClear = true;
        let prev = unit.pos;
        for (const wp of chain) {
          if (allBlockers.some((o) => segmentHitsRect(prev, wp, o, padding))) {
            pathClear = false;
            break;
          }
          prev = wp;
        }
        if (pathClear) {
          bestPos = candidate;
          bestWaypoints = chain;
          break;
        }
      }
      unit.waypoints = bestWaypoints.length > 0 ? bestWaypoints : [bestPos];
    }
  }
  tick = (ticker) => {
    if (!this.running) return;
    const rawDt = ticker.deltaMS / 1e3;
    this.renderer?.renderUnits(this.units, rawDt, this.ctfState ?? void 0, this._phase === "playing");
    if (this.ctfState) {
      this.renderer?.renderFlags(this.ctfState);
    }
    this.pathDrawer?.updateHover();
    if (this._phase !== "playing") return;
    if (this.endingBattle) {
      this.endDelayTimer -= rawDt;
      this.renderer?.effects?.update(rawDt);
      if (this.endDelayTimer <= 0) {
        this.endBattle(this.pendingWinner);
      }
      return;
    }
    this.accumulator += rawDt * this.speedMultiplier;
    while (this.accumulator >= FIXED_DT) {
      this.simulationStep(FIXED_DT);
      this.accumulator -= FIXED_DT;
    }
    this.renderer?.renderProjectiles(this.projectiles);
    this.renderer?.effects?.update(rawDt);
    this.onEvent("update", { phase: "playing", timeLeft: Math.max(0, this.roundTimer) });
  };
  /** Run one fixed-timestep simulation step. */
  simulationStep(dt) {
    this.elapsedTime += dt;
    this.roundTimer -= dt;
    this.simulationTick++;
    const redDelayed = this.updateHordeDelay(dt);
    this.updateChaseAI();
    this.updateMovement(dt, redDelayed);
    this.updateCombat(dt);
    const hits = this.updateProjectiles(dt);
    this.dispatchHitEffects(hits);
    this.handleBomberChainExplosions(hits);
    this.recordFrame();
    if (this.checkCtfCapture()) return;
    if (this.checkElimination()) return;
    this.checkRoundEnd(dt);
  }
  /** Horde start delay -- skip red movement for 2s so player can react. */
  updateHordeDelay(dt) {
    const redDelayed = this.hordeStartDelay > 0;
    if (redDelayed) this.hordeStartDelay -= dt;
    return redDelayed;
  }
  /** Zombies, shielders, and bombers on the red team always chase closest enemy. */
  updateChaseAI() {
    for (const unit of this.units) {
      if (!unit.alive || unit.team !== "red" || unit.type !== "zombie" && unit.type !== "shielder" && unit.type !== "bomber") continue;
      const target = findTarget(unit, this.units, null, this.obstacles);
      if (target) {
        unit.waypoints = [];
        unit.moveTarget = { x: target.pos.x, y: target.pos.y };
      }
    }
  }
  /** Advance waypoints and move all living units. */
  updateMovement(dt, redDelayed) {
    for (const unit of this.units) {
      if (!unit.alive) continue;
      if (redDelayed && unit.team === "red") continue;
      advanceWaypoint(unit, dt);
      moveUnit(unit, dt, this.obstacles, this.units, this.rng);
    }
    separateUnits(this.units, this.obstacles);
  }
  /** Auto-target nearest enemy, fire projectiles, handle melee blades. */
  updateCombat(dt) {
    for (const unit of this.units) {
      if (!unit.alive) continue;
      const target = findTarget(unit, this.units, null, this.obstacles);
      if (unit.type === "blade") {
        if (target) {
          const desired = Math.atan2(target.pos.y - unit.pos.y, target.pos.x - unit.pos.x);
          updateGunAngle(unit, desired, dt);
        }
        const aoeHits = bladeAoeAttack(unit, this.units, dt);
        for (const hit of aoeHits) {
          this.replayEvents.push({
            frame: this.replayFrames.length,
            type: hit.killed ? "kill" : "hit",
            pos: hit.pos,
            angle: unit.gunAngle,
            damage: hit.damage,
            flanked: false,
            team: hit.team,
            targetId: hit.targetId
          });
        }
        continue;
      }
      const canShoot = target && isInRange(unit, target, this.elevationZones) && hasLineOfSight(unit.pos, target.pos, this.obstacles, unit.projectileRadius);
      if (canShoot) {
        const desired = Math.atan2(target.pos.y - unit.pos.y, target.pos.x - unit.pos.x);
        updateGunAngle(unit, desired, dt);
        const projectiles = tryFireProjectile(unit, target, dt, this.elevationZones);
        if (projectiles.length > 0) {
          this.projectiles.push(...projectiles);
          this.renderer?.effects?.addMuzzleFlash(unit.pos, unit.gunAngle, unit.radius);
          this.replayEvents.push({
            frame: this.replayFrames.length,
            type: "fire",
            pos: { x: unit.pos.x, y: unit.pos.y },
            angle: unit.gunAngle,
            damage: projectiles[0].damage,
            flanked: false,
            team: unit.team
          });
        }
      } else {
        unit.fireTimer = Math.max(0, unit.fireTimer - dt);
        if (target) {
          const desired = Math.atan2(target.pos.y - unit.pos.y, target.pos.x - unit.pos.x);
          updateGunAngle(unit, desired, dt);
        } else {
          const speed = Math.sqrt(unit.vel.x * unit.vel.x + unit.vel.y * unit.vel.y);
          if (speed > 1) {
            const desired = Math.atan2(unit.vel.y, unit.vel.x);
            updateGunAngle(unit, desired, dt);
          }
        }
      }
    }
  }
  /** Update projectile positions and resolve collisions. Returns hit results. */
  updateProjectiles(dt) {
    const { alive: aliveProjectiles, hits } = updateProjectiles(this.projectiles, this.units, dt, this.obstacles);
    this.projectiles = aliveProjectiles;
    return hits;
  }
  /** Trigger visual effects for projectile hits and record replay events. */
  dispatchHitEffects(hits) {
    const fx = this.renderer?.effects ?? null;
    for (const hit of hits) {
      const unitGfx = this.renderer?.getUnitContainer(hit.targetId);
      if (unitGfx) fx?.addHitFlash(unitGfx);
      this.replayEvents.push({
        frame: this.replayFrames.length,
        type: hit.killed ? "kill" : "hit",
        pos: { ...hit.pos },
        angle: hit.angle,
        damage: hit.damage,
        flanked: hit.flanked,
        team: hit.team,
        targetId: hit.targetId
      });
      const victimTeam = hit.team === "blue" ? "red" : "blue";
      const effectDamage = hit.flanked ? hit.damage * 1.5 : hit.damage;
      fx?.addBloodSpray(hit.pos, hit.angle, victimTeam, effectDamage);
      if (hit.killed) {
        fx?.addKillText(hit.pos, hit.team);
        fx?.addBloodBurst(hit.pos, hit.angle, victimTeam, effectDamage);
      }
    }
  }
  /** Handle bomber chain explosions when bombers are killed. */
  handleBomberChainExplosions(hits) {
    const fx = this.renderer?.effects ?? null;
    for (const hit of hits) {
      if (hit.killed) {
        const deadUnit = this.units.find((u) => u.id === hit.targetId);
        if (deadUnit && deadUnit.type === "bomber") {
          fx?.addExplosion(deadUnit.pos, 80);
          const explosionHits = bomberExplode(deadUnit, this.units);
          for (const eh of explosionHits) {
            this.replayEvents.push({
              frame: this.replayFrames.length,
              type: eh.killed ? "kill" : "hit",
              pos: eh.pos,
              angle: 0,
              damage: eh.damage,
              flanked: false,
              team: deadUnit.team,
              targetId: eh.targetId
            });
            if (eh.killed) {
              const chainDead = this.units.find((u) => u.id === eh.targetId);
              if (chainDead?.type === "bomber") {
                fx?.addExplosion(chainDead.pos, 80);
              }
            }
          }
        }
      }
    }
  }
  /** Check CTF capture win condition. Returns true if the round ended. */
  checkCtfCapture() {
    if (!this.ctfMode || !this.ctfState) return false;
    updateCtfFlags(this.ctfState, this.units);
    const capturer = checkCtfCapture(this.ctfState);
    if (capturer) {
      this.ctfState.winner = capturer;
      this.endingBattle = true;
      this.endDelayTimer = 0.6;
      this.pendingWinner = capturer;
      this.projectiles = [];
      this.renderer?.renderProjectiles([]);
      return true;
    }
    return false;
  }
  /** Check elimination win condition. Returns true if the round ended. */
  checkElimination() {
    const blueAlive2 = this.units.filter((u) => u.alive && u.team === "blue").length;
    const redAlive = this.units.filter((u) => u.alive && u.team === "red").length;
    if (blueAlive2 === 0 || redAlive === 0) {
      if (redAlive === 0 && this.hordeMode) {
        this.running = false;
        this.renderer?.ticker.remove(this.tick, this);
        this.projectiles = [];
        this.renderer?.renderProjectiles([]);
        this.pathDrawer?.disable();
        this.pathDrawer?.clearGraphics();
        this.onEvent("wave-clear");
        return true;
      }
      this.endingBattle = true;
      this.endDelayTimer = 0.6;
      this.pendingWinner = blueAlive2 === 0 ? "red" : "blue";
      this.projectiles = [];
      this.renderer?.renderProjectiles([]);
      return true;
    }
    return false;
  }
  /** Check if action is complete and transition back to planning phase.
   *  Skipped in lockstep mode — host is authoritative for round transitions. */
  checkRoundEnd(dt) {
    if (this.lockstepMode) return;
    const idle = this.projectiles.length === 0 && this.units.every((u) => {
      if (!u.alive) return true;
      const speed = u.vel.x * u.vel.x + u.vel.y * u.vel.y;
      if (speed > 1 || u.waypoints.length > 0) return false;
      const target = findTarget(u, this.units, null, this.obstacles);
      return !target || !isInRange(u, target, this.elevationZones);
    });
    this.idleTime = idle ? this.idleTime + dt : 0;
    if (this.roundTimer <= 0 || this.idleTime >= 0.5) {
      this.projectiles = [];
      this.renderer?.renderProjectiles([]);
      this.roundNumber++;
      this.setPhase("blue-planning");
    }
  }
  recordFrame() {
    const frame = {
      units: this.units.map((u) => ({
        id: u.id,
        type: u.type,
        team: u.team,
        x: u.pos.x,
        y: u.pos.y,
        vx: u.vel.x,
        vy: u.vel.y,
        gunAngle: u.gunAngle,
        hp: u.hp,
        maxHp: u.maxHp,
        alive: u.alive,
        radius: u.radius
      })),
      projectiles: this.projectiles.map((p) => ({
        x: p.pos.x,
        y: p.pos.y,
        vx: p.vel.x,
        vy: p.vel.y,
        damage: p.damage,
        radius: p.radius,
        team: p.team,
        maxRange: p.maxRange,
        distanceTraveled: p.distanceTraveled,
        trail: p.trail ? p.trail.map((t) => ({ ...t })) : void 0
      }))
    };
    if (this.ctfState) {
      frame.blueFlag = {
        x: this.ctfState.blueFlag.pos.x,
        y: this.ctfState.blueFlag.pos.y,
        homeX: this.ctfState.blueFlag.homePos.x,
        homeY: this.ctfState.blueFlag.homePos.y,
        carrierId: this.ctfState.blueFlag.carrierId,
        dropped: this.ctfState.blueFlag.dropped
      };
      frame.redFlag = {
        x: this.ctfState.redFlag.pos.x,
        y: this.ctfState.redFlag.pos.y,
        homeX: this.ctfState.redFlag.homePos.x,
        homeY: this.ctfState.redFlag.homePos.y,
        carrierId: this.ctfState.redFlag.carrierId,
        dropped: this.ctfState.redFlag.dropped
      };
    }
    this.replayFrames.push(frame);
  }
  getReplayData() {
    if (this.replayFrames.length === 0) return null;
    return {
      frames: this.replayFrames,
      events: this.replayEvents,
      obstacles: this.obstacles,
      elevationZones: this.elevationZones,
      ctfMode: this.ctfMode || void 0
    };
  }
  endBattle(winner) {
    this.running = false;
    this.renderer?.ticker.remove(this.tick, this);
    this.projectiles = [];
    this.renderer?.renderProjectiles([]);
    this.pathDrawer?.disable();
    this.pathDrawer?.clearGraphics();
    this.renderer?.effects?.clear();
    const blueAlive2 = this.units.filter((u) => u.alive && u.team === "blue").length;
    const redAlive = this.units.filter((u) => u.alive && u.team === "red").length;
    const blueTotal = this.units.filter((u) => u.team === "blue").length;
    const redTotal = this.units.filter((u) => u.team === "red").length;
    this.onEvent("end", {
      winner,
      blueAlive: blueAlive2,
      redAlive,
      blueKilled: redTotal - redAlive,
      redKilled: blueTotal - blueAlive2,
      duration: this.elapsedTime
    });
  }
  /** Start simulation directly in 'playing' state (for guest lockstep).
   *  Bypasses planning phases — call after loadOnlineGameState + setPaths.
   *  Pass the host's per-round seed (from OnlineWaypointData) so the guest's
   *  PRNG matches the host exactly; the guest can't derive it locally because
   *  its headless engine doesn't track the round number. */
  startPlaying(roundSeed) {
    this.running = true;
    this.lockstepMode = true;
    this._phase = "playing";
    this.roundTimer = ROUND_DURATION_S;
    this.idleTime = 0;
    this.accumulator = 0;
    this.simulationTick = 0;
    this.endingBattle = false;
    this.pendingWinner = null;
    this.rng = createRng(roundSeed ?? this.seed + this.roundNumber);
    this.replayFrames = [];
    this.replayEvents = [];
  }
  /** Drive the engine externally (for headless mode). Pass real deltaMS. */
  externalTick(deltaMS) {
    this.tick({ deltaMS });
  }
  getSimulationTick() {
    return this.simulationTick;
  }
  /** Get replay events starting from the given index (for dispatching effects). */
  getReplayEventsSince(startIndex) {
    const events = this.replayEvents.slice(startIndex);
    return { events, nextIndex: this.replayEvents.length };
  }
  /** Set waypoints for a team's units. Validates and caps input from remote peer. */
  setPaths(team, paths) {
    const maxWaypoints = 100;
    for (const p of paths) {
      if (!Array.isArray(p.waypoints)) continue;
      const unit = this.units.find((u) => u.id === p.unitId);
      if (unit && unit.team === team) {
        const valid = p.waypoints.slice(0, maxWaypoints).filter(
          (w) => typeof w.x === "number" && typeof w.y === "number" && Number.isFinite(w.x) && Number.isFinite(w.y)
        );
        unit.waypoints = valid;
      }
    }
  }
  setBluePaths(paths) {
    this.setPaths("blue", paths);
  }
  /** Load full game state from an OnlineGameState snapshot (for guest sync).
   *  Caps array sizes defensively — the snapshot comes from an untrusted peer. */
  loadOnlineGameState(state) {
    this.obstacles = state.obstacles.slice(0, MAX_ONLINE_OBSTACLES);
    this.elevationZones = state.elevationZones.slice(0, MAX_ONLINE_ELEVATION_ZONES);
    this.units = state.units.slice(0, MAX_ONLINE_UNITS).map((u) => createUnitFromState(u));
    this.projectiles = [];
    this.replayFrames = [];
    this.replayEvents = [];
  }
  setSpeed(multiplier) {
    this.speedMultiplier = multiplier;
  }
  getAliveCount() {
    return {
      blue: this.units.filter((u) => u.alive && u.team === "blue").length,
      red: this.units.filter((u) => u.alive && u.team === "red").length
    };
  }
  getCtfState() {
    return this.ctfState;
  }
  getUnits() {
    return this.units;
  }
  getProjectiles() {
    return this.projectiles;
  }
  getMapData() {
    return { obstacles: this.obstacles, elevationZones: this.elevationZones };
  }
  setRedPaths(paths) {
    this.setPaths("red", paths);
  }
  getOnlineGameState() {
    return {
      units: this.units.map((u) => ({
        id: u.id,
        type: u.type,
        team: u.team,
        x: u.pos.x,
        y: u.pos.y,
        hp: u.hp,
        maxHp: u.maxHp,
        radius: u.radius,
        speed: u.speed,
        range: u.range,
        gunAngle: u.gunAngle
      })),
      obstacles: this.obstacles,
      elevationZones: this.elevationZones,
      mapWidth: MAP_WIDTH,
      mapHeight: MAP_HEIGHT
    };
  }
  /** Generate a fresh standard PvP starting state (army + map) headlessly, for
   *  seeding an async match's authoritative initial state at creation time. */
  static generateInitialState() {
    const engine = new _GameEngine(null, () => {
    });
    engine.startBattle();
    const state = engine.getOnlineGameState();
    engine.stop();
    return state;
  }
  /** Deterministically resolve one async round to its authoritative end state.
   *  Runs the fixed-timestep simulation in a tight loop — stopping when a side
   *  is eliminated or `maxTicks` is reached — so the result is independent of
   *  frame pacing and identical on every client. The animated playback shown to
   *  the player is purely cosmetic; THIS is what gets persisted. */
  static resolveRound(startState, bluePaths, redPaths, seed, maxTicks) {
    const e = new _GameEngine(null, () => {
    }, { seed });
    e.loadOnlineGameState(startState);
    e.setBluePaths(bluePaths);
    e.setRedPaths(redPaths);
    e.startPlaying();
    while (e.simulationTick < maxTicks) {
      e.simulationStep(FIXED_DT);
      const blueAlive3 = e.units.some((u) => u.alive && u.team === "blue");
      const redAlive2 = e.units.some((u) => u.alive && u.team === "red");
      if (!blueAlive3 || !redAlive2) break;
    }
    const blueAlive2 = e.units.some((u) => u.alive && u.team === "blue");
    const redAlive = e.units.some((u) => u.alive && u.team === "red");
    return { endState: e.getOnlineGameState(), gameOver: !blueAlive2 || !redAlive };
  }
  stop() {
    this.running = false;
    this.renderer?.ticker.remove(this.tick, this);
    this.pathDrawer?.destroy();
    this.pathDrawer = null;
    this.renderer?.effects?.clear();
    this.renderer?.clearCtfGraphics();
  }
};

// src/online-async-core.ts
function fnv1a(hash, value) {
  hash ^= value & 255;
  hash = Math.imul(hash, 16777619);
  hash ^= value >>> 8 & 255;
  hash = Math.imul(hash, 16777619);
  hash ^= value >>> 16 & 255;
  hash = Math.imul(hash, 16777619);
  hash ^= value >>> 24 & 255;
  return Math.imul(hash, 16777619);
}
function fnv1aString(hash, s) {
  for (let i = 0; i < s.length; i++) hash = fnv1a(hash, s.charCodeAt(i));
  return hash;
}
function canonicalisePaths(paths) {
  return [...paths].map((p) => ({ unitId: p.unitId, waypoints: p.waypoints })).sort((a, b) => a.unitId < b.unitId ? -1 : a.unitId > b.unitId ? 1 : 0);
}
function hashPaths(paths) {
  let h = 2166136261;
  for (const p of canonicalisePaths(paths)) {
    h = fnv1aString(h, p.unitId);
    h = fnv1a(h, p.waypoints.length);
    for (const w of p.waypoints) {
      h = fnv1a(h, Math.round(w.x * 100));
      h = fnv1a(h, Math.round(w.y * 100));
    }
  }
  return h >>> 0;
}
function deriveMatchSeed(roomId, blueHash, redHash) {
  let h = 2166136261;
  h = fnv1aString(h, roomId);
  h = fnv1a(h, blueHash);
  h = fnv1a(h, redHash);
  return h >>> 0 & 2147483647;
}
function verifyReveal(turn) {
  if (turn.paths == null) return false;
  return hashPaths(turn.paths) === turn.commitHash;
}

// src/engine-entry.ts
function resolveRound(startState, bluePaths, redPaths, seed, maxTicks) {
  return GameEngine.resolveRound(startState, bluePaths, redPaths, seed, maxTicks);
}
function blueAlive(state) {
  return state.units.some((u) => u.team === "blue" && u.hp > 0);
}
export {
  ROUND_DURATION_S,
  blueAlive,
  canonicalisePaths,
  deriveMatchSeed,
  hashPaths,
  resolveRound,
  verifyReveal
};
